version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "FoodOrder"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-g9i6rrmh50x3"
s3_prefix = "FoodOrder"
region = "ap-southeast-2"
capabilities = "CAPABILITY_IAM"
